paaro_architectures:
  x86_64: amd64
  aarch64: arm64

dijets_binaries_dir: "paaro-{{ paaro_version }}"

paaro_architecture: "{{ paaro_architectures[ansible_facts.architecture] }}"
paaro_archive: "paaro-{{ paaro_os }}-{{ paaro_architecture }}-{{ paaro_version }}.tar.gz"
paaro_release: "{{ paaro_releases.json | rejectattr('prerelease') | first }}"
paaro_os: "{{ ansible_facts.system | lower }}"
paaro_version: "{{ paaro_release.tag_name }}"

paaro_signer_keyid: D93080B0C0D5FE8B
paaro_signer_pubkey: "{{ lookup('file', 'paaro.gpg.key') }}"

repo_url: https://github.com/lasthyphen/paaro
repo_api_base: https://api.github.com
