- name: Query releases
  uri:
    url: "{{ repo_api_base }}/repos{{ repo_url | urlsplit('path') }}/releases"
  register: paaro_releases
  changed_when: false
  check_mode: false

- name: Fetch release
  get_url:
    url: "{{ repo_url }}/releases/download/{{ paaro_version }}/{{ item.file }}"
    dest: ./
  loop:
    - file: "{{ paaro_archive }}"
    - file: "{{ paaro_archive }}.sig"
  loop_control:
    label: "{{ item.file }}"

- name: Verify release
  block:
    - name: Create temp gnupghome
      tempfile:
        state: directory
        suffix: gpg
      register: dijets_download_gnupghome

    - name: Import keys
      environment:
        GNUPGHOME: "{{ dijets_download_gnupghome.path }}"
      command:
        cmd: gpg --import
        stdin: "{{ paaro_signer_pubkey }}"

    - name: Verify signature
      environment:
        GNUPGHOME: "{{ dijets_download_gnupghome.path }}"
      command:
        cmd: gpg --trusted-key "{{ paaro_signer_keyid }}" --verify "{{ paaro_archive }}.sig" "{{ paaro_archive }}"
      changed_when: false
  always:
    - name: Cleanup temp gnupghome
      file:
        path: "{{ dijets_download_gnupghome.path }}"
        state: absent

- name: Unpack release
  unarchive:
    src: "{{ paaro_archive }}"
    dest: ./
    remote_src: true
  loop:
    - file: "{{ paaro_archive }}"
  loop_control:
    label: "{{ item.file }}"
