#!/usr/bin/env ansible-playbook
---
- name: Update the network
  connection: ssh
  hosts: all
  roles:
    - name: dijets_stop
    - name: dijets_build
    - name: dijets_reset
    - name: dijets_start
